//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakultetiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesori
    {
        public int id_p { get; set; }
        public string emri_p { get; set; }
        public string mbiemri_p { get; set; }
        public string titulli_p { get; set; }
        public string nrtel_p { get; set; }
        public string email_p { get; set; }
    }
}
