//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakultetiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Lendet
    {
        public int id_l { get; set; }
        public string emri_l { get; set; }
        public Nullable<int> ligjerata { get; set; }
        public Nullable<int> ushtrime { get; set; }
        public Nullable<int> ects { get; set; }
        public Nullable<int> id_p { get; set; }
        public string emri_p { get; set; }
        public string mbiemri_p { get; set; }
    }
}
